import test from "node:test";
import assert from "node:assert/strict";
import {canonicalize,deriveReceiptId,unsignedReceipt} from "../verification/verifier-core.mjs";
import {MAX_REGISTRY_BYTES,unsignedRegistry,validateRegistryStructure,verifyInputs,verifyReceiptWithRegistry,verifyRegistry} from "../verification/registry-core.mjs";
import {BUNDLED_DEMO_TRUST_REGISTRY} from "../verification/bundled-trust-registry.mjs";
import {TRUSTED_DEMO_RECEIPT} from "../verification/trusted-demo-receipt.mjs";
import {REGISTRY_AUTHORITY_PRIVATE_JWK} from "./fixtures/registry-authority-private-key.mjs";
import {DEVELOPMENT_PRIVATE_JWK} from "./fixtures/development-private-key.mjs";

const enc=new TextEncoder(),clone=structuredClone,b64=v=>Buffer.from(v).toString("base64url"),NOW="2026-07-30T13:00:00Z";
async function signRegistry(change=r=>r){const r=clone(BUNDLED_DEMO_TRUST_REGISTRY);change(r);const key=await crypto.subtle.importKey("jwk",REGISTRY_AUTHORITY_PRIVATE_JWK,{name:"ECDSA",namedCurve:"P-256"},false,["sign"]);r.signature=b64(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},key,enc.encode(canonicalize(unsignedRegistry(r)))));return r;}
async function signReceipt(change=r=>r){const r=clone(TRUSTED_DEMO_RECEIPT);change(r);r.receipt_id=await deriveReceiptId(r);const key=await crypto.subtle.importKey("jwk",DEVELOPMENT_PRIVATE_JWK,{name:"ECDSA",namedCurve:"P-256"},false,["sign"]);r.signature=b64(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},key,enc.encode(canonicalize(unsignedReceipt(r)))));return r;}

test("valid signed registry and trusted receipt fully verify",async()=>{assert.equal((await verifyRegistry(BUNDLED_DEMO_TRUST_REGISTRY,{now:NOW})).acceptable,true);assert.equal((await verifyReceiptWithRegistry(TRUSTED_DEMO_RECEIPT,BUNDLED_DEMO_TRUST_REGISTRY,{now:NOW})).overall,"Fully verified");});
test("invalid registry signature fails",async()=>{const r=clone(BUNDLED_DEMO_TRUST_REGISTRY);r.signature=(r.signature[0]==="A"?"B":"A")+r.signature.slice(1);assert.equal((await verifyRegistry(r,{now:NOW})).checks.registry_signature.state,"fail");});
test("unknown authority cannot authenticate",async()=>{const r=await signRegistry(x=>x.authority_id="authority:unknown-root");const out=await verifyRegistry(r,{now:NOW});assert.equal(out.checks.registry_authority.state,"unknown");assert.equal(out.acceptable,false);});
test("stale registry is incomplete",async()=>{const r=await signRegistry(x=>x.next_update="2026-07-01T00:00:00Z");assert.equal((await verifyRegistry(r,{now:NOW})).checks.registry_freshness.state,"unknown");});
test("unsupported registry version is rejected",()=>{const r=clone(BUNDLED_DEMO_TRUST_REGISTRY);r.registry_schema_version="dar-trust-registry-demo-2.0";assert.match(validateRegistryStructure(r).errors.join(" "),/Unsupported registry version/);});
test("rollback sequence is rejected",async()=>assert.equal((await verifyRegistry(BUNDLED_DEMO_TRUST_REGISTRY,{now:NOW,minimumSequence:3})).checks.registry_sequence.state,"fail"));

for(const [status,want] of [["active","Fully verified"],["suspended","Verification incomplete"],["revoked","Verification failed"],["retired","Verification incomplete"],["unknown","Verification incomplete"]])test(`issuer ${status}`,async()=>{const r=await signRegistry(x=>x.issuers[0].status=status);assert.equal((await verifyReceiptWithRegistry(TRUSTED_DEMO_RECEIPT,r,{now:NOW})).overall,want);});
for(const [status,want] of [["expired","Verification incomplete"],["revoked","Verification failed"],["compromised","Verification incomplete"],["suspended","Verification incomplete"],["retired","Verification incomplete"],["unknown","Verification incomplete"]])test(`key ${status}`,async()=>{const r=await signRegistry(x=>{x.signing_keys[0].current_status=status;x.signing_keys[0].status_effective_at="2026-08-01T00:00:00Z";x.signing_keys[0].reason_code=status==="compromised"?"confirmed-compromise":"unknown";});assert.equal((await verifyReceiptWithRegistry(TRUSTED_DEMO_RECEIPT,r,{now:NOW})).overall,want);});
test("receipt before compromise is explicit and incomplete",async()=>{const r=await signRegistry(x=>{x.signing_keys[0].current_status="compromised";x.signing_keys[0].status_effective_at="2026-08-01T00:00:00Z";x.signing_keys[0].reason_code="confirmed-compromise";});const out=await verifyReceiptWithRegistry(TRUSTED_DEMO_RECEIPT,r,{now:NOW});assert.match(out.checks.key_current_status.detail,/later compromised/);assert.equal(out.overall,"Verification incomplete");});
test("receipt after compromise fails despite valid signature",async()=>{const receipt=await signReceipt(x=>x.event_time="2026-08-02T00:00:00Z");const r=await signRegistry(x=>{x.next_update="2027-02-01T00:00:00Z";x.signing_keys[0].current_status="compromised";x.signing_keys[0].status_effective_at="2026-08-01T00:00:00Z";x.signing_keys[0].reason_code="confirmed-compromise";});const out=await verifyReceiptWithRegistry(receipt,r,{now:"2026-08-03T00:00:00Z"});assert.equal(out.checks.receipt_signature.state,"pass");assert.match(out.checks.key_current_status.detail,/after compromise/);assert.equal(out.overall,"Verification failed");});
test("replacement key is identified after retirement",async()=>{const r=await signRegistry(x=>{x.signing_keys[0].current_status="retired";x.signing_keys[0].status_effective_at="2026-08-01T00:00:00Z";x.signing_keys[0].reason_code="planned-retirement";});assert.match((await verifyReceiptWithRegistry(TRUSTED_DEMO_RECEIPT,r,{now:NOW})).checks.key_current_status.detail,/key:trusted-demo-2027/);});
test("event outside key interval fails",async()=>{const receipt=await signReceipt(x=>x.event_time="2025-12-31T23:00:00Z");assert.equal((await verifyReceiptWithRegistry(receipt,BUNDLED_DEMO_TRUST_REGISTRY,{now:NOW})).checks.key_event_validity.state,"fail");});
test("unknown issuer is never fully verified",async()=>{const receipt=await signReceipt(x=>x.issuer_id="issuer:not-registered");assert.notEqual((await verifyReceiptWithRegistry(receipt,BUNDLED_DEMO_TRUST_REGISTRY,{now:NOW})).overall,"Fully verified");});

test("malformed and oversized registries are rejected",async()=>{assert.equal((await verifyInputs(JSON.stringify(TRUSTED_DEMO_RECEIPT),"{",{now:NOW})).overall,"Invalid input");assert.equal((await verifyInputs(JSON.stringify(TRUSTED_DEMO_RECEIPT)," ".repeat(MAX_REGISTRY_BYTES+1),{now:NOW})).overall,"Invalid input");});
test("unknown registry field is rejected",()=>{const r=clone(BUNDLED_DEMO_TRUST_REGISTRY);r.unbounded="no";assert.match(validateRegistryStructure(r).errors.join(" "),/unknown field/);});
test("unsupported registry and key algorithms are rejected",()=>{for(const change of [r=>r.signature_algorithm="none",r=>r.signing_keys[0].algorithm="none"]){const r=clone(BUNDLED_DEMO_TRUST_REGISTRY);change(r);assert.match(validateRegistryStructure(r).errors.join(" "),/Unsupported|unsupported/);}});
test("missing fields and placeholder content cannot fully verify",async()=>assert.notEqual((await verifyReceiptWithRegistry({signature:"placeholder"},{},{now:NOW})).overall,"Fully verified"));

test("JCS vectors cover Unicode, escaping, nesting, ordering, arrays, and numeric edges",()=>{const a={z:[3,{"é":"line\nquote\"",a:true}],n:-0,small:1e-7,big:1e20};const b={big:100000000000000000000,small:0.0000001,n:0,z:[3,{a:true,"é":"line\nquote\""}]};assert.equal(canonicalize(a),canonicalize(b));assert.equal(canonicalize({"😀":1,"a":2}),'{"a":2,"😀":1}');});
for(const value of [NaN,Infinity,-Infinity,undefined,1n])test(`JCS rejects unsupported value ${String(value)}`,()=>assert.throws(()=>canonicalize(value)));
