import { canonicalize, deriveReceiptId, unsignedReceipt, validateStructure as validateReceiptStructure } from "./verifier-core.mjs";
import { DEMO_REGISTRY_TRUST_ROOTS } from "./registry-trust-root.mjs";

export const MAX_REGISTRY_BYTES=64*1024;
export const REGISTRY_SCHEMA_VERSION="dar-trust-registry-demo-1.0";
const ALG="ECDSA_P256_SHA256";
const issuerStatuses=new Set(["active","suspended","revoked","retired","unknown"]);
const keyStatuses=new Set(["active","expired","revoked","compromised","suspended","retired","unknown"]);
const reasonCodes=new Set(["none","routine-expiration","planned-retirement","administrative-revocation","suspected-compromise","confirmed-compromise","issuer-suspension","unknown"]);
const registryFields=["registry_schema_version","registry_id","authority_id","sequence","issued_at","next_update","issuers","signing_keys","signature_algorithm","signature"];
const issuerFields=["issuer_id","display_name","status","registered_at","approved_receipt_schemas","signing_key_refs"];
const keyFields=["issuer_id","signing_key_id","public_key_jwk","algorithm","valid_from","valid_until","current_status","status_effective_at","reason_code","replacement_key_id"];
const jwkFields=["kty","crv","x","y","ext","key_ops"];
const timestamp=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/;
const id={registry:/^registry:[a-z0-9][a-z0-9.-]{2,63}$/,authority:/^authority:[a-z0-9][a-z0-9.-]{2,63}$/,issuer:/^issuer:[a-z0-9][a-z0-9.-]{2,63}$/,key:/^key:[A-Za-z0-9._-]{3,64}$/};
const res=(state,detail)=>Object.freeze({state,detail});
const utf8=(v)=>new TextEncoder().encode(v);
function from64(v){if(!/^[A-Za-z0-9_-]+$/.test(v))throw new Error("Invalid base64url");const s=v.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-v.length%4)%4);return Uint8Array.from(atob(s),c=>c.charCodeAt(0));}
function ordinary(v){return v&&typeof v==="object"&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype;}
function unknownFields(obj,allowed,label,errors){for(const field of Object.keys(obj))if(!allowed.includes(field))errors.push(`${label} unknown field: ${field}.`);}
function time(value,label,errors){if(typeof value!=="string"||value.length>24||!timestamp.test(value)||Number.isNaN(Date.parse(value)))errors.push(`${label} must be a UTC RFC 3339 timestamp.`);}

export function unsignedRegistry(registry){const copy={};for(const field of registryFields)if(field!=="signature"&&Object.hasOwn(registry,field))copy[field]=registry[field];return copy;}
export function parseRegistryText(text){if(typeof text!=="string")return{ok:false,errors:["Registry input must be text."]};if(utf8(text).byteLength>MAX_REGISTRY_BYTES)return{ok:false,errors:[`Registry exceeds ${MAX_REGISTRY_BYTES} bytes.`]};let value;try{value=JSON.parse(text);}catch{return{ok:false,errors:["Malformed registry JSON."]}}if(!ordinary(value))return{ok:false,errors:["Registry must be an ordinary JSON object."]};return{ok:true,value};}

export function validateRegistryStructure(r){const errors=[];if(!ordinary(r))return{ok:false,errors:["Registry must be an object."]};unknownFields(r,registryFields,"Registry",errors);for(const f of registryFields)if(!Object.hasOwn(r,f))errors.push(`Registry missing field: ${f}.`);if(r.registry_schema_version!==REGISTRY_SCHEMA_VERSION)errors.push(`Unsupported registry version: ${String(r.registry_schema_version)}.`);if(typeof r.registry_id!=="string"||!id.registry.test(r.registry_id))errors.push("Invalid registry_id.");if(typeof r.authority_id!=="string"||!id.authority.test(r.authority_id))errors.push("Invalid authority_id.");if(!Number.isInteger(r.sequence)||r.sequence<1||r.sequence>2147483647)errors.push("Invalid registry sequence.");time(r.issued_at,"issued_at",errors);time(r.next_update,"next_update",errors);if(r.signature_algorithm!==ALG)errors.push("Unsupported registry signature algorithm.");if(typeof r.signature!=="string"||!/^[A-Za-z0-9_-]{80,100}$/.test(r.signature))errors.push("Invalid registry signature format.");
  if(!Array.isArray(r.issuers)||r.issuers.length<1||r.issuers.length>100)errors.push("issuers must contain 1 to 100 records.");else for(const [i,v] of r.issuers.entries()){if(!ordinary(v)){errors.push(`Issuer ${i} must be an object.`);continue}unknownFields(v,issuerFields,`Issuer ${i}`,errors);if(typeof v.issuer_id!=="string"||!id.issuer.test(v.issuer_id))errors.push(`Issuer ${i} has invalid ID.`);if(typeof v.display_name!=="string"||v.display_name.length<1||v.display_name.length>80)errors.push(`Issuer ${i} has invalid display name.`);if(!issuerStatuses.has(v.status))errors.push(`Issuer ${i} has unsupported status.`);time(v.registered_at,`Issuer ${i} registered_at`,errors);if(!Array.isArray(v.approved_receipt_schemas)||v.approved_receipt_schemas.length<1||v.approved_receipt_schemas.length>16||v.approved_receipt_schemas.some(x=>typeof x!=="string"||x.length>40))errors.push(`Issuer ${i} has invalid approved schemas.`);if(!Array.isArray(v.signing_key_refs)||v.signing_key_refs.length<1||v.signing_key_refs.length>32||v.signing_key_refs.some(x=>typeof x!=="string"||!id.key.test(x)))errors.push(`Issuer ${i} has invalid key references.`);}
  if(!Array.isArray(r.signing_keys)||r.signing_keys.length<1||r.signing_keys.length>500)errors.push("signing_keys must contain 1 to 500 records.");else for(const [i,v] of r.signing_keys.entries()){if(!ordinary(v)){errors.push(`Key ${i} must be an object.`);continue}unknownFields(v,keyFields,`Key ${i}`,errors);if(typeof v.issuer_id!=="string"||!id.issuer.test(v.issuer_id)||typeof v.signing_key_id!=="string"||!id.key.test(v.signing_key_id))errors.push(`Key ${i} has invalid identity.`);if(v.algorithm!==ALG)errors.push(`Key ${i} has unsupported algorithm.`);time(v.valid_from,`Key ${i} valid_from`,errors);if(v.valid_until!==undefined)time(v.valid_until,`Key ${i} valid_until`,errors);if(!keyStatuses.has(v.current_status))errors.push(`Key ${i} has unsupported status.`);time(v.status_effective_at,`Key ${i} status_effective_at`,errors);if(!reasonCodes.has(v.reason_code))errors.push(`Key ${i} has unsupported reason code.`);if(v.replacement_key_id!==undefined&&(typeof v.replacement_key_id!=="string"||!id.key.test(v.replacement_key_id)))errors.push(`Key ${i} has invalid replacement key.`);if(!ordinary(v.public_key_jwk)){errors.push(`Key ${i} has invalid public JWK.`);}else{unknownFields(v.public_key_jwk,jwkFields,`Key ${i} JWK`,errors);const j=v.public_key_jwk;if(j.kty!=="EC"||j.crv!=="P-256"||j.ext!==true||JSON.stringify(j.key_ops)!=='["verify"]'||typeof j.x!=="string"||j.x.length!==43||typeof j.y!=="string"||j.y.length!==43)errors.push(`Key ${i} has invalid public JWK.`);}}
  return{ok:errors.length===0,errors};}

export async function verifyRegistry(registry,options={}){const roots=options.roots??DEMO_REGISTRY_TRUST_ROOTS;const now=new Date(options.now??Date.now());const structure=validateRegistryStructure(registry);const checks={registry_structure:res(structure.ok?"pass":"fail",structure.ok?"Registry structure is valid.":structure.errors.join(" ")),registry_signature:res("unknown","Not evaluated."),registry_authority:res("unknown","Not evaluated."),registry_freshness:res("unknown","Not evaluated."),registry_sequence:res("unknown","Not evaluated.")};if(!structure.ok)return{acceptable:false,fatal:true,checks,registry};const root=roots.find(x=>x.authority_id===registry.authority_id&&x.algorithm===registry.signature_algorithm);checks.registry_authority=res(root?"pass":"unknown",root?"Registry authority is recognized by the bundled trust root.":"Registry authority is unknown.");if(root){try{const key=await crypto.subtle.importKey("jwk",root.public_key_jwk,{name:"ECDSA",namedCurve:"P-256"},false,["verify"]);const ok=await crypto.subtle.verify({name:"ECDSA",hash:"SHA-256"},key,from64(registry.signature),utf8(canonicalize(unsignedRegistry(registry))));checks.registry_signature=res(ok?"pass":"fail",ok?"Registry signature is valid.":"Registry signature is invalid.");}catch{checks.registry_signature=res("fail","Registry signature is malformed or unverifiable.");}}const fresh=now>=new Date(registry.issued_at)&&now<new Date(registry.next_update);checks.registry_freshness=res(fresh?"pass":"unknown",fresh?"Registry is within its freshness window.":"Registry status unknown or stale.");const min=options.minimumSequence??0;const sequenceOk=registry.sequence>=min;checks.registry_sequence=res(sequenceOk?"pass":"fail",sequenceOk?`Registry sequence ${registry.sequence} is acceptable.`:`Registry sequence ${registry.sequence} is older than accepted sequence ${min}; rollback attempt rejected.`);const authentic=checks.registry_signature.state==="pass"&&checks.registry_authority.state==="pass";return{acceptable:authentic&&fresh&&sequenceOk,fatal:checks.registry_signature.state==="fail"||checks.registry_sequence.state==="fail",checks,registry};}

function issuerEffect(status){if(status==="active")return["pass","Issuer is active."];if(status==="suspended")return["unknown","Issuer currently suspended."];if(status==="revoked")return["fail","Issuer registration is revoked."];if(status==="retired")return["unknown","Issuer is retired; historical evidence requires policy review."];return["unknown","Issuer status is unknown."];}
function keyEffect(key,event,now){const effective=new Date(key.status_effective_at);const before=event<effective;if(key.valid_until&&now>=new Date(key.valid_until)&&key.current_status==="active")return["unknown","Key expired after issuance; registry status has not yet been updated."];switch(key.current_status){case"active":return["pass","Current key status is active."];case"expired":return["unknown",before?"Key expired after issuance.":"Receipt event is not trusted under an expired key."];case"retired":return["unknown",before?`Key retired after issuance.${key.replacement_key_id?` Replacement: ${key.replacement_key_id}.`:""}`:"Receipt was issued after retirement-effective time."];case"suspended":return["unknown","Key is currently suspended."];case"revoked":return["fail","Key is administratively revoked."];case"compromised":return[before?"unknown":"fail",before?"Valid at event time, but key later compromised.":"Issued after compromise-effective time."];default:return["unknown","Current key status is unknown."];}}

export async function verifyReceiptWithRegistry(receipt,registry,options={}){const reg=await verifyRegistry(registry,options);const receiptStructure=validateReceiptStructure(receipt);const checks={...reg.checks,receipt_structure:res(receiptStructure.ok?"pass":"fail",receiptStructure.ok?"Receipt structure is valid.":receiptStructure.errors.join(" ")),content_integrity:res("unknown","Not evaluated."),issuer_recognized:res("unknown","Not evaluated."),issuer_status:res("unknown","Not evaluated."),key_recognized:res("unknown","Not evaluated."),key_event_validity:res("unknown","Not evaluated."),key_current_status:res("unknown","Not evaluated."),receipt_signature:res("unknown","Not evaluated.")};if(!receiptStructure.ok||reg.fatal)return{overall:"Verification failed",checks};if(!reg.acceptable)return{overall:"Verification incomplete",checks};const expected=await deriveReceiptId(receipt);checks.content_integrity=res(expected===receipt.receipt_id?"pass":"fail",expected===receipt.receipt_id?"Content integrity is valid.":"Receipt ID does not match canonical content.");const issuer=registry.issuers.find(x=>x.issuer_id===receipt.issuer_id);checks.issuer_recognized=res(issuer?"pass":"unknown",issuer?"Issuer is present in the signed registry.":"Issuer is unknown.");if(!issuer)return{overall:checks.content_integrity.state==="fail"?"Verification failed":"Verification incomplete",checks};const [is,idetail]=issuerEffect(issuer.status);checks.issuer_status=res(is,idetail);const key=registry.signing_keys.find(x=>x.issuer_id===receipt.issuer_id&&x.signing_key_id===receipt.signing_key_id&&issuer.signing_key_refs.includes(x.signing_key_id));checks.key_recognized=res(key?"pass":"unknown",key?"Signing key is bound to the issuer.":"Signing key is unknown or not bound to the issuer.");if(!key)return{overall:"Verification incomplete",checks};const event=new Date(receipt.event_time),from=new Date(key.valid_from),until=key.valid_until?new Date(key.valid_until):null,eventValid=event>=from&&(!until||event<until);checks.key_event_validity=res(eventValid?"pass":"fail",eventValid?"Key was valid at receipt event time.":"Event is outside the key validity interval.");const [ks,kdetail]=keyEffect(key,event,new Date(options.now??Date.now()));checks.key_current_status=res(ks,kdetail);try{const pub=await crypto.subtle.importKey("jwk",key.public_key_jwk,{name:"ECDSA",namedCurve:"P-256"},false,["verify"]);const sig=await crypto.subtle.verify({name:"ECDSA",hash:"SHA-256"},pub,from64(receipt.signature),utf8(canonicalize(unsignedReceipt(receipt))));checks.receipt_signature=res(sig?"pass":"fail",sig?"Receipt mathematical signature is valid.":"Receipt mathematical signature is invalid.");}catch{checks.receipt_signature=res("fail","Receipt signature is malformed.");}
  const required=["registry_structure","registry_signature","registry_authority","registry_freshness","registry_sequence","receipt_structure","content_integrity","issuer_recognized","issuer_status","key_recognized","key_event_validity","key_current_status","receipt_signature"];const full=required.every(k=>checks[k].state==="pass");const failed=required.some(k=>checks[k].state==="fail");return{overall:full?"Fully verified":failed?"Verification failed":"Verification incomplete",checks};}

export async function verifyInputs(receiptText,registryText,options={}){let receipt;try{receipt=JSON.parse(receiptText);}catch{return{overall:"Invalid input",checks:{receipt_structure:res("fail","Malformed receipt JSON.")}}}const parsed=parseRegistryText(registryText);if(!parsed.ok)return{overall:"Invalid input",checks:{registry_structure:res("fail",parsed.errors.join(" "))}};return verifyReceiptWithRegistry(receipt,parsed.value,options);}
